units metal
boundary p p p
atom_style atomic
read_data AlLi.lammps-data
Reading data file ...
  triclinic box = (0 0 0) to (26.954922 23.343648 22.008602) with tilt (13.477461 13.477461 7.7812158)
WARNING: Triclinic box skew is large. LAMMPS will run inefficiently. (src/domain.cpp:221)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  864 atoms
  read_data CPU = 0.187 seconds
pair_style grace/fs extrapolation
[GRACE/FS]
[GRACE-FS] Version: 2025.12.4p1
[GRACE-FS] Product evaluator is used
pair_coeff * * /home/users/lysogy36/PycharmProjects/GITHUB/grace-tutorial-colab-Sept2026/fps-variant/3-distill/student-gamma-le-5/seed/1/saved_model.yaml /home/users/lysogy36/PycharmProjects/GITHUB/grace-tutorial-colab-Sept2026/fps-variant/3-distill/student-gamma-le-5/seed/1/saved_model.asi Al Li
[GRACE-FS] Loading /home/users/lysogy36/PycharmProjects/GITHUB/grace-tutorial-colab-Sept2026/fps-variant/3-distill/student-gamma-le-5/seed/1/saved_model.yaml
[GRACE-FS] Supporting 2 elements: Al Li 
[GRACE-FS] Number of functions per element: 205 
[GRACE-FS] Mapping LAMMPS atom type #1(Al) -> ACE species type #0
[GRACE-FS] Mapping LAMMPS atom type #2(Li) -> ACE species type #1
[GRACE-FS] Loading ASI /home/users/lysogy36/PycharmProjects/GITHUB/grace-tutorial-colab-Sept2026/fps-variant/3-distill/student-gamma-le-5/seed/1/saved_model.asi
neighbor 2.0 bin
neigh_modify delay 0 every 1 check yes
fix     grace_gamma all pair 25 grace/fs gamma 1
compute max_gamma all reduce max f_grace_gamma
compute dist all pair/local dist
compute min_dist all reduce min c_dist inputs local
variable maxg equal c_max_gamma
variable dump_skip equal "c_max_gamma < 1.5"
dump extrap all custom 25 extrapolative_structures.dump id type x y z f_grace_gamma
dump_modify extrap skip v_dump_skip element Al Li
fix stopper all halt 25 v_maxg > 25 error continue
thermo_style custom step temp pe etotal press vol c_min_dist c_max_gamma cpu cpuremain
thermo 25
thermo_modify flush yes
velocity all create 500.0 12345 mom yes rot yes dist gaussian
timestep 0.001
fix npt_ramp all npt temp 500 5000 0.025 aniso 0 0 1.0
run 500

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:

- KOKKOS package: https://doi.org/10.1145/3731599.3767498

@inproceedings{Johansson25,
 author = {A. Johansson and E. Weinberg and C. Trott and M. McCarthy and S. Moore},
 title = {{LAMMPS-KOKKOS}: {P}erformance Portable Molecular Dynamics Across Exascale Architectures},
 year = 2025,
 booktitle = {Proceedings of the SC '25 Workshops of the International Conference for High Performance Computing,
  Networking, Storage and Analysis},
 pages = {1217–1232},
}

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Neighbor list info ...
  update: every = 1 steps, delay = 0 steps, check = yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 8
  ghost atom cutoff = 8
  binsize = 8, bins = 7 4 3
  2 neighbor lists, perpetual/occasional/extra = 1 1 0
  (1) pair grace/fs/kk, perpetual
      attributes: full, newton on, kokkos_device
      pair build: full/bin/kk/device
      stencil: full/bin/3d
      bin: kk/device
  (2) compute pair/local, occasional
      attributes: half, newton on
      pair build: half/bin/atomonly/newton/tri
      stencil: half/bin/3d/tri
      bin: standard
WARNING: Fix pair not compatible with sending data in Kokkos communication (src/KOKKOS/comm_kokkos.cpp:934)
WARNING: Fix with atom-based arrays not compatible with sending data in Kokkos communication, switching to legacy exchange/border communication (src/KOKKOS/comm_kokkos.cpp:941)
WARNING: Fix pair not (yet) compatible with Kokkos sorting on device (src/KOKKOS/atom_kokkos.cpp:219)
WARNING: Fix with atom-based arrays not (yet) compatible with Kokkos sorting on device, switching to legacy host sorting (src/KOKKOS/atom_kokkos.cpp:225)
Per MPI rank memory allocation (min/avg/max) = 229 | 229 | 229 Mbytes
   Step          Temp          PotEng         TotEng         Press          Volume       c_min_dist    c_max_gamma        CPU          CPULeft    
         0   500           -2604.7615     -2548.9857      1057.8192      13848.389      2.7510752      0.65212179     0              0            
        25   141.01534     -2560.5392     -2544.8087      9880.8383      13858.896      2.3043147      1.3944227      0.45017808     8.553395     
        50   329.20208     -2572.9357     -2536.2127      6640.4378      13918.821      2.4075144      0.97839028     0.87326549     7.8593929    
        75   340.09154     -2559.8669     -2521.9291      5673.4789      14022.737      2.3191614      1.2177639      1.2970762      7.3501005    
       100   441.03567     -2551.5246     -2502.3264      4981.1379      14160.524      2.2509585      1.1152039      1.7400766      6.9603075    
       125   570.33228     -2541.2881     -2477.6667      4664.2581      14326          2.1567555      1.8288041      2.1640389      6.4921176    
       150   688.71776     -2520.4233     -2443.5958      5066.9236      14511.907      2.1820229      2.8358596      2.5986224      6.0634529    
       175   965.53342     -2508.4696     -2400.7629      4972.2845      14711.29       2.2285265      3.2237335      3.0321794      5.631191     
       200   1095.5909     -2468.0573     -2345.8425      9780.7613      14919.543      1.9462154      10.389386      3.4661475      5.1992219    
       225   1356.3369     -2434.7655     -2283.464       15079.345      15155.616      2.0363647      7.2693735      3.8972687      4.7633287    
       250   1636.5215     -2391.4543     -2208.8979      20148.003      15441.18       1.9236063      7.9273104      4.3133573      4.3133577    
       275   2054.7661     -2352.5385     -2123.3263      25432.433      15789.597      1.8728614      17.146384      4.7276529      3.8680799    
Fix halt condition for fix-id stopper met on step 300 with value 57.92400930386818
       300   2372.6709     -2293.1045     -2028.4295      30694.541      16208.851      1.6897066      57.924009      5.1381243      3.4254164    
Loop time of 5.13923 on 1 procs for 300 steps with 864 atoms

Performance: 5.044 ns/day, 4.759 hours/ns, 58.375 timesteps/s, 50.436 katom-step/s
99.3% CPU use with 1 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 4.7433     | 4.7433     | 4.7433     |   0.0 | 92.30
Neigh   | 0.011949   | 0.011949   | 0.011949   |   0.0 |  0.23
Comm    | 0.011362   | 0.011362   | 0.011362   |   0.0 |  0.22
Output  | 0.066429   | 0.066429   | 0.066429   |   0.0 |  1.29
Modify  | 0.29426    | 0.29426    | 0.29426    |   0.0 |  5.73
Other   |            | 0.01197    |            |       |  0.23

Nlocal:            864 ave         864 max         864 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:           3301 ave        3301 max        3301 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:          49709 ave       49709 max       49709 min
Histogram: 1 0 0 0 0 0 0 0 0 0
FullNghs:        99834 ave       99834 max       99834 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 99834
Ave neighs/atom = 115.54861
Neighbor list builds = 12
Dangerous builds = 0
[grace/fs] Not enough statistics
Total wall time: 0:00:06
